version: '3.6'
services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: 'secret'
    app_go:
        build:
            context: .
            dockerfile: Dockerfile
        image: app_go
        ports:
            - '8000:8000'
        depends_on:
            - 'db'
        environment:
            IP: '0.0.0.0'
            PORT: '8000'
            POSTGRES_URL: 'db'
            POSTGRES_PASSWORD: 'secret'
