version: '3.6'

services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: 'secret'
        volumes:
            - './db-data/:/var/lib/postgresql/data'
        user: '1000:1000'
    app_go:
        build:
            context: .
            dockerfile: Dockerfile
        image: app_go
        volumes:
            - './blockchain.html:/blockchain.html'
        ports:
            - '8000:8000'
        depends_on:
            - 'db'
        environment:
            IP: '0.0.0.0'
            PORT: '8000'
            POSTGRES_URL: 'db'
            POSTGRES_PASSWORD: 'secret'
    swagger:
        image: swaggerapi/swagger-ui
        volumes:
            - './openapi.yml:/openapi.yml'
        ports:
            - '8080:8080'
        environment:
            SWAGGER_JSON: '/openapi.yml'
            API_URL: 'openapi.yml'
